#!/usr/bin/env bash
# Installing nginx
brew install nginx
sudo brew services restart nginx
echo 'Hello World!' | nano /var/www/html/index.html

findit="\tlocation / {"
replace="\tlocation /redirect_me {\n\t\treturn 301 \$scheme://https://youtu.be/uTyu3HwL-7Y;\n\t}\n\n\tlocation / {"
#adds return statement to nginx/sites-available./default folder with sed command. redirects to youtube.
sudo sed -i "s@^$findit@$replace@" /etc/nginx/sites-available/default
sudo service nginx restart