#!/usr/bin/env bash
# Installs nginx with redirect
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
echo 'Hello World' | sudo tee /var/www/html/index.html
findit="\tlocation / {"
replace="\tlocation /redirect_me {\n\t\treturn 301 \$scheme://https://www.youtube.com/results?search_query=introduction+to+mysql+%3B%5Cn%5Ct;\n\t}\n\n\tlocation / {"
#adds return statement to nginx/sites-available./default folder with sed command. redirects to youtube.
sudo sed -i "s@^$findit@$replace@" /etc/nginx/sites-available/default
sudo service nginx restart