#!/usr/bin/env bash
#Write a Bash script that displays Holberton School 10 times, but for the 9th OBiteration, displays Holberton School and then Hi on a new line

i=0
while [ $i -ne 9 ]
do
 echo Holberton School
 ((i++))
 
 if [ $i -eq 8 ]
 then
     echo Holberton School
     echo Hi

fi
done
