#!/usr/bin/env bash
#Write a Bash script that loops from 1 to 10 and

i=1

while [ $i -ne 11 ]
do

   ((i++))
   if [ $i -eq 5 ]
   then
       echo bad luck
   elif [ $i -eq 9 ]
   then
       echo good luck
   else [ $i -eq 10 ]
	echo Holberton School

       
   fi
   
done

    
