#!/usr/bin/env bash
#Write a Bash script that displays the time for 12 hours and 59 minutes:

H=0
M=1

while [ $H -lt 13 ];
do
echo "Hour: $H"
((H++))
M=1
	while [ $M -lt 60 ];
	do
	echo $M
	((M++))
        done
done