#!/usr/bin/env bash
#gives information about the holbertonshool file

y="holbertonschool"

if [ ! -e $y ]; then echo "$y file does not exist"; else echo "$y file exists";

if [ ! -s $y ]; then ecno "$y file is empy"; else echo "$y file is not empty"; fi

if [ -f $y ]; then echo "$y is a regular file"; fi; fi
