#!/usr/bin/env bash
# Installing HAproxy

sudo apt-get -y update
sudo apt-get -y upgrade

sudo apt-get -y install haproxy

str="\nfrontend http_web\n\tbind *:80\n\tstats uri /haproxy?stats\n\tdefault_backend custom_backend\n\nbackend custom_backend\n\tbalance roundrobin\n\tserver web-01 3.89.163.85 check\n\tserver web-02 54.89.159.97 check"
sudo echo -e $str | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart